---

- name: Check mount is mounted
  shell: df -h | grep {{ glusterfs_brick_disk }} | awk '{print $6}'
  register: mount_result
  ignore_errors: true
  changed_when: false

- block:
  - name: Init xfs filesystem
    filesystem:
      fstype: 'xfs'
      dev: '{{ glusterfs_brick_disk }}'
      opts: '-i size=512'

  - name: Create glsuterfs dir
    file:
      path: '{{ glusterfs_brick_path }}'
      state: directory
      owner: root
      group: root

  - name: Mount device to directory
    mount:
      path: '{{ glusterfs_brick_path }}'
      src: '{{ glusterfs_brick_disk }}'
      fstype: 'xfs'
      dump: '1'
      passno: '2'
      backup: yes
      state: mounted
  when: not mount_result.stdout

