---

#- name: apply common configuration to all nodes
#  hosts: all

#  roles:
#    - common

#- name: Install MySQL server in dbservers
#  hosts: mysql

#  roles:
#    - mysql

#- name: Install Redis in dbservers
#  hosts: redis

#  roles:
#    - redis

#- name: Install mongodb in dbservers
#  hosts: mongodb

#  roles:
#    - mongodb

- name: Install glusterfs in dbservers
  hosts: glusterfs

  roles:
    - glusterfs