---
# Install and configurate nginx server.

- name: Install nginx
  yum: name={{ item }} state=present
  with_items:
    - nginx
    #- php-mysql
    - libsemanage-python
    - libselinux-python

- name: Start nginx
  service: name=nginx state=started enabled=yes

- name: Create Nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx.conf
  notify: restart nginx

- name: Create Nginx index.html
  template: src=index.html.j2 dest=/usr/share/nginx/html

- name: Add webservers iptables rule
  iptables: action=insert table=filter chain=INPUT
            protocol=tcp  destination_port={{ httpd_port }}
            jump=ACCEPT comment="Accept Nginx connections."
  notify: restart iptables
  tags: iptables